// <auto-generated />
namespace CosmeticaShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class easyDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(easyDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201712021932120_easy-DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
