// <auto-generated />
namespace CosmeticaShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class productsIsDeleteProp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productsIsDeleteProp));
        
        string IMigrationMetadata.Id
        {
            get { return "201801141618124_productsIsDeleteProp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
